{% set version = "5.15.7" %}

package:
  name: qt-svg
  version: {{ version }}

source:
  url: https://download.qt.io/official_releases/qt/{{ version.rpartition('.')[0] }}/{{ version }}/submodules/qtsvg-everywhere-opensource-src-{{ version }}.tar.xz
  sha256: 3a8179a1e8f991c1bb0feaed97808ee1192ef1e7fb8821637ed16a6ee09770f2

build:
  number: 0
  detect_binary_files_with_prefix: true
  skip: true  # [win]
  skip: true  # [linux]
  skip: true  # [osx and x86]
  run_exports:
    - {{ pin_subpackage('qt-svg', max_pin='x.x') }}

requirements:
  build:
    - cmake
    - make                               # [unix]
    - jom                                # [win]
    - ninja
    - perl
    - {{ compiler('cxx') }}
    - {{ compiler('c') }}
    # - qt-base                            # [build_platform != target_platform]
    - sysroot_linux-64 2.17              # [linux]
    - {{ cdt('xorg-x11-proto-devel') }}  # [linux]
    - {{ cdt('libx11-devel') }}          # [linux]
    - {{ cdt('libxext') }}               # [linux]
    - {{ cdt('libxext-devel') }}         # [linux]
    - {{ cdt('libxrender-devel') }}      # [linux]
    - {{ cdt('mesa-libgl-devel') }}      # [linux]
    - {{ cdt('mesa-libegl') }}           # [linux]
    - {{ cdt('mesa-libegl-devel') }}     # [linux]
    - {{ cdt('mesa-dri-drivers') }}      # [linux]
    - {{ cdt('libxau-devel') }}          # [linux]
    - {{ cdt('alsa-lib-devel') }}        # [linux]
    - {{ cdt('gtk2-devel') }}            # [linux]
    - {{ cdt('gtkmm24-devel') }}         # [linux]
    - {{ cdt('libdrm-devel') }}          # [linux]
    - {{ cdt('libxcomposite-devel') }}   # [linux]
    - {{ cdt('libxcursor-devel') }}      # [linux]
    - {{ cdt('libxi-devel') }}           # [linux]
    - {{ cdt('libxrandr-devel') }}       # [linux]
    - {{ cdt('pciutils-devel') }}        # [linux]
    - {{ cdt('libxscrnsaver-devel') }}   # [linux]
    - {{ cdt('libxtst-devel') }}         # [linux]
    - {{ cdt('libselinux') }}            # [linux]
    - {{ cdt('libselinux-devel') }}      # [linux]
    - {{ cdt('libxdamage') }}            # [linux]
    - {{ cdt('libxdamage-devel') }}      # [linux]
    - {{ cdt('libxfixes') }}             # [linux]
    - {{ cdt('libxfixes-devel') }}       # [linux]
    - {{ cdt('libxxf86vm') }}            # [linux]
    - {{ cdt('libxxf86vm-devel') }}      # [linux]
    - {{ cdt('libsm-devel') }}           # [linux]
    - {{ cdt('libice-devel') }}          # [linux]
    - {{ cdt('libxcb') }}                # [linux]
    - {{ cdt('libxcb-devel') }}          # [linux]
    - {{ cdt('expat-devel') }}           # [linux]
    - {{ cdt('pcre') }}                  # [linux]
    - {{ cdt('libglvnd-glx') }}          # [linux]
    - {{ cdt('libglvnd-egl') }}          # [linux]
    - {{ cdt('libxkbcommon-devel') }}    # [linux]
    - {{ cdt('xcb-util-devel') }}        # [linux]
    - {{ cdt('xcb-util-image-devel') }}  # [linux]
    - {{ cdt('xcb-util-keysyms-devel') }}     # [linux]
    - {{ cdt('xcb-util-renderutil-devel') }}  # [linux]
    - {{ cdt('xcb-util-wm-devel') }}          # [linux]
    # libclang is required in order to enable simultaneous x86_64 and
    # arm64 support for QDoc
    # - libclang                           # [arm64]
    # Although these should be host-only dependencies, they are needed when
    # cross-compiling arm64 binaries on x86_64 since llvm-config (host/arm64)
    # cannot be executed on x86_64 to locate libclang successfully
    - llvmdev                           # [arm64]
    - clangdev                          # [arm64]
  host:
    - qt-base
    - llvmdev
    - clangdev
    - libclang
    - zlib

  run_constrained:
    - __osx >={{ MACOSX_DEPLOYMENT_TARGET|default("10.14") }}  # [osx and x86_64]
test:
  requires:
    - sysroot_linux-64 2.17              # [linux]
    - {{ cdt('xorg-x11-proto-devel') }}  # [linux]
    - {{ cdt('libx11-devel') }}          # [linux]
    - {{ cdt('libxext') }}               # [linux]
    - {{ cdt('libxext-devel') }}         # [linux]
    - {{ cdt('libxrender-devel') }}      # [linux]
    - {{ cdt('mesa-libgl-devel') }}      # [linux]
    - {{ cdt('mesa-libegl') }}           # [linux]
    - {{ cdt('mesa-libegl-devel') }}     # [linux]
    - {{ cdt('mesa-dri-drivers') }}      # [linux]
    - {{ cdt('libxau-devel') }}          # [linux]
    - {{ cdt('alsa-lib-devel') }}        # [linux]
    - {{ cdt('gtk2-devel') }}            # [linux]
    - {{ cdt('gtkmm24-devel') }}         # [linux]
    - {{ cdt('libdrm-devel') }}          # [linux]
    - {{ cdt('libxcomposite-devel') }}   # [linux]
    - {{ cdt('libxcursor-devel') }}      # [linux]
    - {{ cdt('libxi-devel') }}           # [linux]
    - {{ cdt('libxrandr-devel') }}       # [linux]
    - {{ cdt('pciutils-devel') }}        # [linux]
    - {{ cdt('libxscrnsaver-devel') }}   # [linux]
    - {{ cdt('libxtst-devel') }}         # [linux]
    - {{ cdt('libselinux-devel') }}      # [linux]
    - {{ cdt('libxdamage') }}            # [linux]
    - {{ cdt('libxdamage-devel') }}      # [linux]
    - {{ cdt('libxfixes') }}             # [linux]
    - {{ cdt('libxfixes-devel') }}       # [linux]
    - {{ cdt('libxxf86vm') }}            # [linux]
    - {{ cdt('libxcb') }}                # [linux]
    - {{ cdt('expat-devel') }}           # [linux]
    - {{ cdt('pcre') }}                  # [linux]
    - {{ cdt('libglvnd-glx') }}          # [linux]
  commands:
    - test -f ${PREFIX}/lib/libQt5Svg${SHLIB_EXT}                     # [unix]
    - test -f ${PREFIX}/plugins/iconengines/libqsvgicon${SHLIB_EXT}   # [unix]
    - test -f ${PREFIX}/plugins/imageformats/libqsvg${SHLIB_EXT}      # [unix]
    - if not exist %LIBRARY_LIB%\Qt5svg_conda.lib exit 1              # [win]
    - if not exist %LIBRARY_BIN%\Qt5svg_conda.dll exit 1              # [win]

about:
  home: http://qt-project.org
  license: LGPL-2.1-or-later
  license_file:
    - LICENSE.LGPLv21
    - LICENSE.LGPLv3
    - LICENSE.LGPL3
  summary: 'qtsvg Qt is a cross-platform application and UI framework.'
  doc_url: http://doc.qt.io/
  dev_url: https://github.com/qt/qtsvg

extra:
  recipe-maintainers:
    - conda-forge/qt-main
